<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>FanControl.ClevoPlugin</AssemblyName>
    <RootNamespace>FanControl.ClevoPlugin</RootNamespace>
    <OutputType>Library</OutputType>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="FanControl.Plugins">
      <HintPath>..\Dlls\FanControl.Plugins.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
